version: '3'

services:
    web:
        build:
            context: ./src
            dockerfile: ./Dockerfile
        volumes:
            - ./src:/code/
        ports:
            - "8000:8000"
        restart: "no"
        depends_on:
          - "db"
        command: ["./start-up-django.sh", "db"]

    db:
        image: postgres:alpine
        ports:
            - 5434:5432
        restart: "no"
        environment:
            - POSTGRES_USER=${DOCKER_COMPOSE_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DOCKER_COMPOSE_POSTGRES_PASSWORD}
            - POSTGRES_DB=${DOCKER_COMPOSE_POSTGRES_DB}

